/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LivroVO;
import service.LivroService;
import service.ServiceFactory;

/**
 *
 * @author windows
 */
public class GUIManuLivro extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"idlivro", "titulo", "subtitulo", "isbn", "autor", "data_lancamento"});
    /**
     * Creates new form GUIManuLivro
     */
    public GUIManuLivro() {
        initComponents();
        preencherTabela();
    }
    
    private void preencherTabela(){
        try {
            //Buscando objeto ProdutoServicos
            LivroService ls = ServiceFactory.getLivroService();
            
            /* Criando um ArrayList<ClienteVO> vazio
             para receber o ArrayList com os dados */
            ArrayList<LivroVO> fli = new ArrayList<>();
            
            //Recebendo o ArrayList cheio em produtos
            fli = ls.buscarLivro();
            
            for(int i = 0; i < fli.size(); i++){
                    dtm.addRow(new String[]{
                    String.valueOf(fli.get(i).getIdlivro()),
                    String.valueOf(fli.get(i).getTitulo()),
                    String.valueOf(fli.get(i).getSubtitulo()),
                    String.valueOf(fli.get(i).getISBN()),
                    String.valueOf(fli.get(i).getAutor()),
                    String.valueOf(fli.get(i).getData_lancamento())
                });
            }
            /* Adicionando o modelo de tabela 
             com os dados na tabela produto */
            jTableLivro.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro !!" + e.getMessage());
        }
    }
    
    private void filtrar(){
        try{
            if(jtPesquisa.getText().isEmpty()){
                limparTabela();
                preencherTabela();  
            }else{
                String filtro = jComboPesquisa.getSelectedItem().toString();
                String query = "";
                
                if(filtro.equalsIgnoreCase("TITULO")){
                    query = "WHERE titulo like '%"+jtPesquisa.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("SUBTITULO")){
                    query = "WHERE subtitulo like '%"+jtPesquisa.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("ISBN")){
                    query = "WHERE isbn like '%"+jtPesquisa.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("AUTOR")){
                    query = "WHERE autor like '%"+jtPesquisa.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("DATA LANÇAMENTO")){
                    query = "WHERE data_lancamento like '%"+jtPesquisa.getText()+"%'";
                }
                
                LivroService ls = ServiceFactory.getLivroService();
                ArrayList<LivroVO> fli = ls.filtra(query);
                
                for(int i = 0; i < fli.size(); i++){
                dtm.addRow(new String[]{
                    String.valueOf(fli.get(i).getIdlivro()),
                    String.valueOf(fli.get(i).getTitulo()),
                    String.valueOf(fli.get(i).getSubtitulo()),
                    String.valueOf(fli.get(i).getISBN()),
                    String.valueOf(fli.get(i).getAutor()),
                    String.valueOf(fli.get(i).getData_lancamento())
                    });
                }
                
                jTableLivro.setModel(dtm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,
                    "Erro!" + e.getMessage());
        }
    }
    
    private void limparTabela() {
    /*Para limpar a tabela temos que setar o número de
      linhas para zero no default table model */        
        dtm.setNumRows(0);
    }//fecha limparTabela

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtPesquisa = new javax.swing.JTextField();
        jComboPesquisa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivro = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();
        jbLimparTabela = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jlSubTitulo = new javax.swing.JLabel();
        jtSubtitulo = new javax.swing.JTextField();
        jlEdicao = new javax.swing.JLabel();
        jtEdicao = new javax.swing.JTextField();
        jlEditora = new javax.swing.JLabel();
        jtEitora = new javax.swing.JTextField();
        jlDataLancamento = new javax.swing.JLabel();
        jftDataLancamento = new javax.swing.JTextField();
        jlISBN = new javax.swing.JLabel();
        jtISBN = new javax.swing.JTextField();
        jlAutor = new javax.swing.JLabel();
        jComboAutor = new javax.swing.JComboBox();
        jtValorVenda = new javax.swing.JTextField();
        jtQuantidade = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jlQuantidade1 = new javax.swing.JLabel();

        setClosable(true);

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jComboPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TITULO", "SUBTITULO", "ISBN", "AUTOR", "ANO LANÇAMENTO" }));
        jComboPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboPesquisaItemStateChanged(evt);
            }
        });

        jTableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITULO", "SUBTITULO", "ISBN", "AUTOR", "ANO LANÇAMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLivro.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLivro);

        jbAtualizar.setText("ATUALIZAR");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbLimparTabela.setText("LIMPAR TABELA");
        jbLimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparTabelaActionPerformed(evt);
            }
        });

        jlTitulo.setText("TITULO");

        jlSubTitulo.setText("SUBTITULO");

        jlEdicao.setText("EDIÇÃO");

        jlEditora.setText("EDITORA");

        jlDataLancamento.setText("ANO DE LANÇAMENTO");

        jlISBN.setText("ISBN");
        jlISBN.setToolTipText("");

        jlAutor.setText("AUTOR");

        jbLimpar.setText("LIMPAR");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCadastrar.setText("CADASTRAR");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jlQuantidade1.setText("QUANTIDADE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbAtualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbLimparTabela))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTitulo)
                    .addComponent(jtSubtitulo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 183, Short.MAX_VALUE)
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboAutor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEdicao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtEdicao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftDataLancamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jlEditora)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtValorVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtEitora)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlISBN)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo)
                            .addComponent(jlSubTitulo)
                            .addComponent(jlDataLancamento)
                            .addComponent(jlAutor)
                            .addComponent(jlQuantidade1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSubTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEdicao)
                            .addComponent(jlEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtEitora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDataLancamento)
                            .addComponent(jlISBN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlQuantidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCadastrar)
                            .addComponent(jbLimpar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbLimparTabela)
                            .addComponent(jbAtualizar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        // TODO add your handling code here:
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jComboPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboPesquisaItemStateChanged
        // TODO add your handling code here:
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jComboPesquisaItemStateChanged

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbLimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparTabelaActionPerformed
        // TODO add your handling code here:
        limparTabela();
    }//GEN-LAST:event_jbLimparTabelaActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboAutor;
    private javax.swing.JComboBox<String> jComboPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivro;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimparTabela;
    private javax.swing.JTextField jftDataLancamento;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlDataLancamento;
    private javax.swing.JLabel jlEdicao;
    private javax.swing.JLabel jlEditora;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlQuantidade1;
    private javax.swing.JLabel jlSubTitulo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtEdicao;
    private javax.swing.JTextField jtEitora;
    private javax.swing.JTextField jtISBN;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTextField jtSubtitulo;
    private javax.swing.JTextField jtTitulo;
    private javax.swing.JTextField jtValorVenda;
    // End of variables declaration//GEN-END:variables
}
